spring:
  application:
    name: mcp-client
  main:
    web-application-type: none
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:7b
          temperature: 0.2
    mcp:
      client:
        enabled: true
        stdio:
          connections:
            server1:
              command: java
              args:
                - -jar
                - /Users/ledvanov/IdeaProjects/mcp-demo/mcp-server/target/mcp-server-1.0-SNAPSHOT.jar

logging:
  file:
    name: logs/mcp-client.log